service: appointments

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

package:
  patterns:
    - "schema.graphql"
    - "appsync.graphql"
    - "mapping-templates"

plugins:
  - serverless-appsync-plugin
  - serverless-appsync-simulator
  - serverless-plugin-typescript
  - serverless-offline

functions:
  getAppointments:
    handler: getAppointments.query
  createAppointment:
    handler: createAppointment.mutation

custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: "../tsconfig.json"
  appsync-simulator:
    location: .build
  appSync:
    name: Appointments
    schema: schema.graphql
    authenticationType: API_KEY
    mappingTemplatesLocation: mapping-templates
    mappingTemplates:
      - dataSource: GetAppointments
        type: Query
        field: getAppointments
        request: Query.getAppointments.request.vtl
        response: Query.getAppointments.response.vtl
      - dataSource: CreateAppointment
        type: Mutation
        field: createAppointment
        request: Mutation.createAppointment.request.vtl
        response: Mutation.createAppointment.response.vtl
    dataSources:
      - type: AWS_LAMBDA
        name: GetAppointments
        config:
          functionName: getAppointments
      - type: AWS_LAMBDA
        name: CreateAppointment
        config:
          functionName: createAppointment
